-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price decimal(10,2) not null,
  currency text default 'USD',
  image_url text, /* Main image */
  category text, /* e.g. 'Bats', 'Jerseys' */
  stock_quantity integer default 0,
  is_featured boolean default false,
  metadata jsonb default '{}'::jsonb /* For sizes, colors, extra specs */
);

-- Enable RLS
alter table public.products enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.products
  for select
  to anon
  using (true);

-- Create policy to allow authenticated users (service role/admin) to insert/update
-- giving anon no write access by default
create policy "Allow service role full access"
  on public.products
  for all
  to service_role
  using (true)
  with check (true);

-- Seed Data
INSERT INTO public.products (name, description, price, category, image_url, stock_quantity, is_featured, metadata)
VALUES
('Men''s Authentic USA Cricket T20 World Cup Jersey', 'Engineered for the modern cricketer. 100% Recycled Polyester.', 85.00, 'Apparel', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAdKxM-bactj7a5x2sbTfXkZ_c0-VqqV3HH0dFvlWlP5pSoqDoPT0jYWiSxCbgm9hwgwJUdKXCg76JQT1c8z77-zTblhWS23pKjbo88La3PUgDhdLt1gTqXBX2PIeL8koYY0UaG78e4gUKjLrl8-PtHAVMl_Oy1l6WSIatjIXsR7YrjSwemtVhniQU3hxipM6l8ngPMbdhTy8lfwzm9RE_K4OH4G5lY8cMd2dAvo7U7xMXlyDqvQo-K_eFB_UE9aM_A2KgijRLM9ns', 100, true, '{"sizes": ["S", "M", "L", "XL", "XXL"], "color": "Navy"}'),
('Pro Series English Willow Bat', 'Grade 1 English Willow for professional performance.', 350.00, 'Equipment', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRpYTVqw1iLLZPW4BOV8oXc8YTByJXVXAeURJ6D3VNU5NdfgsXRSJfYkD0aIyRniRI_EigGVYQsjNeE78ouwY6bJEMPIWgq4FrSu_5Wd5xGkXir7DkNYwfk1UC_515r3c6GqD5Tg6bT6AEg2SoAsSBHi5RR4Un0Z3IdMeVrTM4ufl0xB8Rl3C0X8gvs3E_810EAC2G-okNVMgKmw4Ix2z8mvsjD5ZzVhhO_LmG60yA9W4rAsyIbu4wI0zeNEL8hFnGJwUSpWVDe7g', 50, true, '{"weight": "2.8 lbs", "grade": "G1"}'),
('USA Training Cap', 'Adjustable performance cap.', 35.00, 'Accessories', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCku8yBbNmRLRZrDF5E5ivFQjsogg_IqJxPAeE8A2K-il3QSk_tM2LNrvvpDXUMy6sBjt5sjbGCGptYLvf2KFnW87k-IdSIsayULxRZP4-XScWmVl4p8DOpcf5PyL0MPwDOIDtXmLIS5Ovt7aqUDAQdSDKPz9L0_QJci_BWmJ999ytDlEdSLKszlGLDvprFIJlGGGZDdGRIwOI1_DxYIbpjCRDhvT0F-Jh8-pf9X3GwMaPVpWR11N6vj0degvT1U3FwziBDcCCEUt0', 200, false, '{"size": "One Size"}'),
('Team Backpack', '25L Capacity with bat sleeve.', 65.00, 'Accessories', 'https://lh3.googleusercontent.com/aida-public/AB6AXuACyvJkyNzl7_Dt81aU0f3p0PSUaQssuxUp2N1JzSha5l3f-GMKogOhd0wiyvS43GvS48HFmMbs6iaKOkS4m1n6DsrGsImFnuxjbwdnC80wjkmXODfYiWgm8EL98waKWHkBorI5n4QY6v-DLGlu-hStbeM84ZtnXB2AybFQJQnkFHxH2qJGpfmW1xYAHjsnqr2PQJ1t2p0V7uqgW3TzJMUo0ORQiCLR7AEi0t4sdcyyvCUqfzVFZiKtEe1CZnX6EYhRRMRbMPMmqBo', 75, false, '{"capacity": "25L"}');

